### ISSUE TITLE
workspace.go:153 error 空数据

### ISSUE THREAD

**Issue by Schmoo2333** [tengfei-xy/wolai#1]
大佬好！我在配置文件里填了cookie，看上去像是正确识别了，但是报错空数据，请问这种情况怎么解决？

`E:\wolai_1.1.1_windows_amd64>wolai.exe
2024-06-15 23:35:57 main.go:56 info  读取配置文件:config.yaml
2024-06-15 23:35:58 user.go:25 info  发现用户:9ekEGnUs4XKBPJTVXFZawn
2024-06-15 23:35:58 workspace.go:153 error 空数据
panic: 空数据

goroutine 1 [running]:
main.main()
        /Users/melta/Documents/source/golang/wolai/main.go:95 +0x6f0`

**Comment by tengfei-xy** [comment]
是企业版嘛？是的话，应该有问题，因为我没有这样的环境，所以比较难支持

**Comment by Schmoo2333** [comment]
> 是企业版嘛？是的话，应该有问题，因为我没有这样的环境，所以比较难支持

不是，是普通的个人版会员的

**Comment by tengfei-xy** [comment]
明日我看看

**Comment by tengfei-xy** [comment]
请尝试新版，[v1.2.0](https://github.com/tengfei-xy/wolai/releases/tag/v1.2.0)
谢谢使用～
